# title: Data Normalization & Classification
# remote_theme: ubc-library-rc/rc-workshop-template
# search_enabled: false
# github_repo_url: "https://github.com/ubc-lib-geo/Data-Normalization-Classification/"

# # license information for workshop content
# license_name: "Creative Commons Attribution 4.0 International License"
# license_url: "http://creativecommons.org/licenses/by/4.0/"
# license_image_url: "https://i.creativecommons.org/l/by/4.0/88x31.png"

# # required for building jekyll site locally
# plugins:
#   - jekyll-remote-theme
#   - jekyll-seo-tag


# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: GIS Workshop Template
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/Data-Normalization-Classification" # the subpath of your site, e.g. /blog
url: "https://ubc-lib-geo.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
remote_theme: pmarsceill/just-the-docs
# theme: "just-the-docs"
color_scheme: light
plugins:
  - jekyll-feed
  - jekyll-seo-tag

footer_content: <a href="https://github.com/ubc-lib-geo/gis-workshop-waml-template" target="_blank">View this workshop in GitHub</a>

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
